
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from tkinter import *
from PIL import Image, ImageTk
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, Toplevel
import staff_login_page
import doctors
import nurses
import shifts
import Rooms_op

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


class StaffHomePage:
    def __init__(self,window):
        self.window = window
        self.window.title("Staff manager homepage")
        self.window.resizable(False, False)
        self.window.geometry("1440x900")
        self.window.state('zoomed')
        self.window.configure(bg = "#FFFFFF")

        frame=Frame(self.window,
            bg = "#FFFFFF",
            height = 700,
            width = 1640,
            bd =0,
            highlightthickness = 0,
            relief = "ridge")
        frame.place(x=0,y=0)
     
        canvas = Canvas(
            self.window,
            bg = "#EEECF1",
            height = 350,
            width = 1550,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
            )
 
        # canvas.create_rectangle(
        #     0.0,
        #     0.0,
        #     1440.0,
        #     900,
        #     fill="#EEECF1",
        #     outline="")
        canvas.place(x=0,y=500)

        button_image_1 = PhotoImage(
            file=relative_to_assets("button_1.png"))

        button_1 = Button(
            self.window,
            image=button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.rooms(),
            relief="flat"
             )

        button_1.image=button_image_1
        button_1.place(
                x=150,
                y=600.0,
                width=275.0,
                height=55.0
                )

        button_image_2 = PhotoImage(
                 file=relative_to_assets("button_2.png"))
        button_2 = Button(
                self.window,
                 image=button_image_2,
                 borderwidth=0,
                 highlightthickness=0,
                 command=lambda:self.shifts(),
                 relief="flat"
                 )
        button_2.image= button_image_2
        button_2.place(
                 x=450,
                 y=600.0,
                 width=275.0,
                 height=55.0
                 )

        button_image_3 = PhotoImage(
                file=relative_to_assets("button_3.png")
                )

        button_3 = Button(
                self.window,
                image=button_image_3,
                borderwidth=0,
                highlightthickness=0,
                command = lambda : self.doctors(),
                relief="flat"
                )
        button_3.image=button_image_3
        button_3.place( x=750, y=600.0, width=275.0, height=55.0)

        button_image_4 = PhotoImage(
                file=relative_to_assets("button_4.png")
                )
        button_4 = Button(
                self.window,
                image=button_image_4,
                borderwidth=0,
                highlightthickness=0,
                command=lambda: self.nurses(),
                relief="flat"
                )
        button_4.image=button_image_4
        button_4.place(
                x=1050,
                y=600.0,
                width=275.0,
                height=55.0
                )

        image_image_1 = Image.open("assets\image_1.png")
        image_resized= image_image_1.resize((1550,510))
        photo = ImageTk.PhotoImage(image_resized)
        # self.image_1 = self.canvas.create_image(
        #     400,
        #     300.0,
        #     image=self.image_resized
        #     )

        image_label=Label(frame,
            bg = "#FFFFFF",
            height = 510,
            width = 1550,
            bd = 0,
            image= photo,
            highlightthickness = 0,
            relief = "ridge")
        image_label.image=photo
        image_label.place(x=0,y=0)
        

        button_image_5 = PhotoImage(
            file=relative_to_assets("button_5.png"))
        button_5 = Button(
            self.window,
            image=button_image_5,
            borderwidth=0,
            bg="white",
            highlightthickness=0,
            command=lambda : self.logout(),
            relief="flat"
            )
        button_5.image=button_image_5
        button_5.place(
            x=1350.0,
            y=5.0,
            width=60.0,
            height=26.0
            )

    def doctors(self):
        win = Toplevel()
        doctors.Doctors(win)
        self.window.withdraw()
        win.deiconify

    def nurses(self):
        win = Toplevel()
        nurses.Nurses(win)
        self.window.withdraw()
        win.deiconify
    
    def shifts(self):
        win = Toplevel()
        shifts.Shifts(win)
        self.window.withdraw()
        win.deiconify

    def rooms(self):
        win = Toplevel()
        Rooms_op.RoomsOp(win)
        self.window.withdraw()
        win.deiconify
        

    def logout(self):
        win=Toplevel()
        staff_login_page.StaffLoginPage(win)
        self.window.withdraw()
        win.deiconify


def staff_homepage():
    window = Tk()
    StaffHomePage(window)
    window.mainloop()


